#!/bin/sh

# Check if other required interfaces are connected, then start snap services
# required interfaces avahi-control(this callback), ppp, log-observe
if snapctl is-connected ppp; then
  if snapctl is-connected log-observe; then
    snapctl start --enable  homebridge
  fi
fi
