#!/bin/bash

logger "$(date '+%Y-%m-%d %H:%M:%S') $0: Entering hook"

# cleanup as migration to the new releases
if [ -d ${SNAP_COMMON}/lib ]; then
  rm -rf ${SNAP_COMMON}/lib ${SNAP_COMMON}/bin ${SNAP_COMMON}/npmrc
fi

# refresh homebridge from snap package
cp -r ${SNAP}/var/lib/homebridge/${NODE_MODULES}/* ${SNAP_COMMON}/${NODE_MODULES}

# check if we should auto update installed modules
. ${SNAP}/bin/homebridge-read-settings
if [ "${HOMEBRIDGE_AUTO_UPDATE_NPM_MODULES}" = "on" ]; then
  cd ${SNAP_COMMON}
  logger $(${SNAP}/opt/homebridge/bin/npm  update)
fi
